
version: "3.9"

services:
  mvc2-php:
    build:
      context: ./volumes/build/php83-fpm
      dockerfile: Dockerfile
    container_name: mvc2-php
    hostname: mvc2-php
    environment:
      PHP_IDE_CONFIG: "serverName=docker.200"

    volumes:
      - ./src:/var/www/html
      - ./volumes/etc/php/xdebug3.ini:/usr/local/etc/php/conf.d/xdebug3.ini
      


  mvc2-nginx:
    build:
      context: ./volumes/build/nginx
      dockerfile: Dockerfile
    container_name: mvc2-nginx
    hostname: mvc2-nginx

    volumes:
      - ./src:/var/www/html
      - ./volumes/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf


    ports:
      - "80:80"

  db:
    container_name: db
    hostname: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: password
    volumes:
      - type: bind
        source: ./volumes/db/db_files
        target: /var/lib/mysql


  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

















#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

